# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13oVVGl25n-jeFhHBO8Njh3FuTWTzkrTM
"""



# =============================================================================
# CSE 400: Fundamentals of Probability in Computing
# Ahmedabad University — School of Engineering and Applied Science (SEAS)
# Group     : s2_g16_fin
# Domain    : Finance and Risk Analysis
# Milestone : 3 — Deterministic Parameter Estimation via MLE
# =============================================================================
#
# BASE REFERENCE:
#   Das, S. (2025). "Predicting Stock Market Crash with Bayesian Generalised
#   Pareto Regression." arXiv:2506.17549.
#   GitHub: github.com/sourish-cmi/quant/tree/main/Predicting_Stock_Market_Crash
#
# MILESTONE-3 CHANGE (confirmed by instructor):
#   System model (GPD Regression) is UNCHANGED from Milestone 2.
#   Only estimation method changes:
#     M2 → Bayesian MAP with Cauchy prior  (probabilistic)
#     M3 → Maximum Likelihood Estimation   (deterministic)
#   Jensen's Inequality was M2 conceptual reasoning — not required here.
#   Separate file from M2, as instructed.
#
# MODEL (Das 2025, Section 3):
#   y_i ~ GPD(mu, sigma_i, xi),   i = 1,...,n
#   log(sigma_i) = x_i^T beta     [log-linear scale link]
#   mu  = 2%   threshold (tail event = daily loss > 2%)
#   xi  = shape parameter (constant across obs)
#   beta = [beta_0, beta_1, beta_2, beta_3]  (intercept + 3 volatility covariates)
#
# LOG-LIKELIHOOD (Das 2025, Section 3.1):
#   log L(xi,beta) = -sum(x_i^T beta)
#                  + (1/xi - 1)*sum(log(1 + xi*(y_i-mu)/exp(x_i^T beta)))
#
# COVARIATES (Das 2025, Section 5):
#   x1 = Nifty 50 EWMA volatility   (domestic)
#   x2 = S&P 500 EWMA volatility    (global equity spillover)
#   x3 = Gold EWMA volatility       (flight-to-safety signal)
#   All standardised: mean=0, std=1
#
# SIMULATION (Das 2025, Section 4):
#   N=100 datasets, n=100 obs, p=5 covariates
#   beta ~ N(0,1), xi ~ Uniform(-0.5, 0.5), sigma=exp(Xbeta)
#   Fit on full dataset, metrics: RMSE(y), RMSE(beta), RMSE(xi), AIC, BIC
# =============================================================================

# ── Install note for Colab ────────────────────────────────────────────────────
# Run this first in Colab:  !pip install yfinance -q
!pip install yfinance -q
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.lines import Line2D
import matplotlib.ticker as mticker

from scipy.optimize import minimize
from scipy.stats   import norm
from sklearn.preprocessing   import StandardScaler

# ── Colab / Jupyter inline rendering ─────────────────────────────────────────
try:
    get_ipython()                          # only exists in IPython / Colab
    import matplotlib
    matplotlib.use("module://matplotlib_inline.backend_inline")
    plt.rcParams["figure.dpi"] = 120
except Exception:
    pass                                   # plain terminal — plt.show() handles it

np.random.seed(42)

# ── Colab-safe show helper ────────────────────────────────────────────────────
def show(fig):
    try:
        from IPython.display import display as ipy_display
        ipy_display(fig)
    except Exception:
        plt.show()
    plt.close(fig)

# =============================================================================
# CONSTANTS  (from paper — do not change)
# =============================================================================
MU    = 2.0    # tail threshold  (loss > 2% triggers tail analysis)
Y0    = 5.0    # crash threshold (loss > 5% = "crash" event)
ALPHA = 0.9    # EWMA smoothing  (Das 2025 Section 2)
K_WIN = 21     # EWMA rolling window (21 trading days ≈ 1 month)

# =============================================================================
# SECTION 1 — DATA
# Replicates Das (2025) Section 2 data pipeline in Python.
# R equivalent: quantmod::getSymbols("^NSEI", src="yahoo")
# =============================================================================

def ewma_vol(returns, k=K_WIN, alpha=ALPHA):
    """
    EWMA empirical volatility — Das (2025) Section 2, Equation 1:
        sigma^2_t = alpha * s^2_{t-1}  +  (1-alpha) * r^2_t
    Annualised: multiply by sqrt(250).
    """
    n   = len(returns)
    vol = np.full(n, np.nan)
    for t in range(k, n):
        s2   = np.var(returns[t - k + 1 : t], ddof=1)
        vol[t] = np.sqrt(alpha * s2 + (1 - alpha) * returns[t]**2) * np.sqrt(250)
    return vol


def garman_klass_vol(H, L, C, O):
    """
    Garman-Klass intraday volatility — Das (2025) Section 2, Equation 2:
        sigma^2_GK = 0.5*(log H/L)^2 - (2*ln2-1)*(log C/O)^2
    Annualised: multiply by sqrt(250).
    """
    gk = 0.5*(np.log(H/L))**2 - (2*np.log(2)-1)*(np.log(C/O))**2
    return np.sqrt(np.abs(gk)) * np.sqrt(250)


def download_data(start="2007-09-17", end="2025-06-13"):
    """
    Download Nifty 50, S&P 500, Gold from Yahoo Finance.
    Equivalent to R: getSymbols(c("^NSEI","^GSPC","GC=F"), src="yahoo")
    Returns None if yfinance unavailable.
    """
    try:
        import yfinance as yf
    except ImportError:
        print("  [!] yfinance not found. In Colab: !pip install yfinance -q")
        return None

    print("Downloading data from Yahoo Finance (same source as GitHub R code) ...")
    tickers = {"NIFTY": "^NSEI", "SP500": "^GSPC", "GOLD": "GC=F"}
    raw = {}
    for name, sym in tickers.items():
        try:
            df = yf.download(sym, start=start, end=end,
                             auto_adjust=True, progress=False)
            if len(df) < 200:
                print(f"  [!] Too few rows for {name}"); return None
            raw[name] = df
            print(f"  {name} ({sym}): {len(df)} trading days  "
                  f"[{df.index[0].date()} → {df.index[-1].date()}]")
        except Exception as e:
            print(f"  [!] Error: {e}"); return None
    return raw


def build_dataset(raw):
    """
    Build modelling dataset from raw OHLCV data.
    Matches Das (2025) Section 5 preprocessing steps exactly.
    """
    def process(df):
        c   = df["Close"].values.flatten()
        ret = np.diff(np.log(c))
        vol = ewma_vol(ret)
        H   = df["High"].values.flatten()[1:]
        L   = df["Low"].values.flatten()[1:]
        C   = df["Close"].values.flatten()[1:]
        O   = df["Open"].values.flatten()[1:]
        gk  = garman_klass_vol(H, L, C, O)
        return pd.DataFrame({"ret": ret, "ewma": vol, "gk": gk},
                             index=df.index[1:])

    ndf = process(raw["NIFTY"])
    sdf = process(raw["SP500"]).rename(columns={"ret":"s_ret","ewma":"sp500_vol","gk":"sp500_gk"})
    gdf = process(raw["GOLD"]).rename(columns={"ret":"g_ret","ewma":"gold_vol","gk":"gold_gk"})

    df = (ndf.join(sdf[["sp500_vol"]], how="left")
             .join(gdf[["gold_vol"]], how="left")
             .rename(columns={"ewma":"nifty_vol"})
             .dropna())

    # Filter: only days where Nifty loss > MU% (tail events)
    tail = df[df["ret"] < -(MU/100)].copy()
    tail["y"] = np.abs(tail["ret"]) * 100     # y in percentage points

    n_total = len(df)
    n_tail  = len(tail)
    n_crash = (tail["y"] > Y0).sum()
    print(f"\n  Total trading days        : {n_total}")
    print(f"  Tail events  (loss > {MU}%) : {n_tail}  ({100*n_tail/n_total:.1f}%)")
    print(f"  Crash events (loss > {Y0}%) : {n_crash}  ({100*n_crash/n_tail:.1f}% of tail)")
    return tail.reset_index(drop=True)


def synthetic_data(n=350):
    """
    Calibrated synthetic fallback when yfinance is unavailable.
    Matches Das (2025) empirical statistics:
      ~4.6% days have loss>2%, ~11.6% of those exceed 5%.
    True params: xi=0.20, beta=[0.7, 0.4, 0.2, 0.15]
    """
    print("  [INFO] Using synthetic data calibrated to Das (2025) statistics.")
    nv = np.clip(np.random.gamma(4.0, 8.0, n), 8, 90)
    sv = np.clip(np.random.gamma(3.5, 6.0, n), 6, 55)
    gv = np.clip(np.random.gamma(2.5, 5.5, n), 4, 50)

    sc  = StandardScaler()
    cov = sc.fit_transform(np.column_stack([nv, sv, gv]))
    Xd  = np.column_stack([np.ones(n), cov])
    bt  = np.array([0.7, 0.4, 0.2, 0.15])
    sig = np.exp(Xd @ bt)
    xi  = 0.20
    u   = np.random.uniform(size=n)
    y   = np.clip(MU + sig/xi*(u**(-xi)-1), MU+1e-6, 30)

    df = pd.DataFrame({"y":y, "nifty_vol":nv, "sp500_vol":sv, "gold_vol":gv})
    print(f"\n  Synthetic tail events     : {n}")
    print(f"  Loss > {Y0}%  fraction     : {(df.y>Y0).mean()*100:.1f}%")
    return df, sc


def prepare():
    """Main data entry point — real data first, synthetic fallback."""
    raw = download_data()
    sc  = None

    if raw is None:
        df, sc = synthetic_data()
    else:
        df = build_dataset(raw)
        if len(df) < 50:
            df, sc = synthetic_data()

    y   = df["y"].values
    cov = df[["nifty_vol","sp500_vol","gold_vol"]].values

    if sc is None:
        sc  = StandardScaler()
        std = sc.fit_transform(cov)
    else:
        std = sc.transform(cov)

    X = np.column_stack([np.ones(len(y)), std])
    return y, X, cov, sc


# =============================================================================
# SECTION 2 — GPD LOG-LIKELIHOOD
# Das (2025) Section 3.1 — exact formula
# =============================================================================

def neg_ll(params, y, X):
    """
    Negative GPD regression log-likelihood (minimise this for MLE).

    Formula (Das 2025, Section 3.1):
      log L(xi, beta) = -sum_i [x_i^T beta]
                      + (1/xi - 1) * sum_i log(1 + xi*(y_i-mu)/exp(x_i^T beta))

    Special case xi→0: reduces to exponential with mean exp(x^T beta).
    Returns +inf for invalid regions (where GPD support is violated).
    """
    xi    = params[0]
    beta  = params[1:]
    lsig  = X @ beta                         # log sigma_i  (n,)
    sigma = np.exp(lsig)
    z     = 1.0 + xi * (y - MU) / sigma     # must be > 0

    if np.any(z <= 0):
        return np.inf

    if abs(xi) < 1e-8:                       # exponential limit
        ll = -np.sum(lsig) - np.sum((y - MU) / sigma)
    else:
        ll = -np.sum(lsig) + (1.0/xi - 1.0) * np.sum(np.log(z))

    return -ll   # negate: scipy minimises, we want to MAXIMISE log-likelihood


# =============================================================================
# SECTION 3 — MLE FITTING
# Key M3 change: no prior term. Pure likelihood maximisation.
# =============================================================================

def fit_mle(y, X):
    """
    Fit GPD Regression via Maximum Likelihood Estimation.

    M2 vs M3 difference:
      M2 minimised: -(log_likelihood + log_prior)   [Bayesian MAP, Cauchy prior]
      M3 minimises: -(log_likelihood)               [Pure MLE, no prior]

    Initialisation (method-of-moments):
      xi_0      = 0.10
      beta_0[0] = log(mean(y-mu) * (1-xi_0))   intercept via MOM
      beta_0[j] = 0  for j > 0

    Constraint: xi < 1 (Smith 1985, cited in Das 2025 Section 3.1)

    Standard errors: from observed Fisher information matrix
      H = numerical Hessian of NLL at MLE
      Cov = H^{-1}
      SE  = sqrt(diag(Cov))
    """
    p   = X.shape[1]
    xi0 = 0.10
    b0  = np.zeros(p)
    b0[0] = np.log(max(np.mean(y - MU) * (1 - xi0), 1e-4))
    x0  = np.concatenate([[xi0], b0])

    result = minimize(neg_ll, x0, args=(y, X),
                      method="L-BFGS-B",
                      bounds=[(-3.0, 0.95)] + [(None,None)]*p,
                      options={"maxiter":10000, "ftol":1e-12, "gtol":1e-7})

    if not result.success or not np.isfinite(result.fun):
        # Gradient-free fallback
        result = minimize(neg_ll, x0, args=(y, X),
                          method="Nelder-Mead",
                          options={"maxiter":100000, "xatol":1e-9, "fatol":1e-9})

    xi_hat   = float(result.x[0])
    beta_hat = result.x[1:]

    # Observed Fisher information (numerical second derivatives)
    h    = 1e-4
    np_  = len(result.x)
    H    = np.zeros((np_, np_))
    for i in range(np_):
        for j in range(i, np_):
            ei = np.zeros(np_); ej = np.zeros(np_)
            ei[i] = h;          ej[j] = h
            fpp = neg_ll(result.x+ei+ej, y, X)
            fpm = neg_ll(result.x+ei-ej, y, X)
            fmp = neg_ll(result.x-ei+ej, y, X)
            fmm = neg_ll(result.x-ei-ej, y, X)
            H[i,j] = H[j,i] = (fpp - fpm - fmp + fmm) / (4*h**2)
    H = 0.5*(H + H.T)
    try:    cov_mat = np.linalg.inv(H)
    except: cov_mat = np.linalg.pinv(H)
    se = np.sqrt(np.abs(np.diag(cov_mat)))

    return result, xi_hat, beta_hat, se


# =============================================================================
# SECTION 4 — PREDICTION
# Das (2025) Section 3 formulas
# =============================================================================

def cond_mean(xi, beta, X):
    """
    E[Y | Y >= mu, x] = mu + exp(x^T beta) / (1 - xi),  xi < 1
    """
    if xi >= 1.0: return np.full(len(X), np.inf)
    return MU + np.exp(X @ beta) / (1.0 - xi)


def crash_prob(xi, beta, X, y0=Y0):
    """
    P(Y > y0 | Y > mu, x) = (1 + xi*(y0-mu)/sigma)^{-1/xi}
    Survival function of GPD — Das (2025) Section 3.
    """
    sigma = np.exp(X @ beta)
    z     = np.clip(1.0 + xi*(y0-MU)/sigma, 1e-10, None)
    return z**(-1.0/xi)


def aic_bic(nll_val, n, k):
    return 2*k + 2*nll_val,  k*np.log(n) + 2*nll_val


# =============================================================================
# SECTION 5 — SIMULATION STUDY
# Replicates Das (2025) Section 4 with MLE instead of MAP
# =============================================================================

def run_simulation(N=100, n=100, p=5):
    """
    Simulation study — Das (2025) Section 4 setup, M3 uses MLE.

    For each of N datasets:
      1. Draw  X ~ N(0,I),  beta ~ N(0,1),  xi ~ Uniform(-0.5, 0.5)
      2. Generate y ~ GPD(mu=2, exp(X*beta), xi)
      3. Fit MLE on 80% train
      4. Evaluate on 20% test

    Metrics (aggregated by median, as in paper):
      RMSE(y)    prediction error on test set
      RMSE(beta) coefficient estimation error
      RMSE(xi)   shape estimation error
      AIC, BIC   in-sample fit (NLL based, no prior)
    """
    rmse_y, rmse_b, rmse_x, aics, bics = [], [], [], [], []
    xi_estimates, xi_trues = [], []

    print(f"\n{'='*60}")
    print(f"  SIMULATION STUDY  (N={N}, n={n}, p={p})")
    print(f"  M3 method: MLE  |  M2 used: Bayesian MAP (Cauchy prior)")
    print(f"  Paper setup: Das (2025) Section 4")
    print(f"{'='*60}")

    for s in range(N):
        Xd   = np.column_stack([np.ones(n), np.random.randn(n, p)])
        bt   = np.random.randn(p+1)
        xit  = np.random.uniform(-0.5, 0.5)
        sig  = np.exp(Xd @ bt)
        u    = np.random.uniform(size=n)
        ysim = (MU - sig*np.log(u) if abs(xit)<1e-8
                else np.clip(MU + sig/xit*(u**(-xit)-1), MU+1e-6, 500))

        idx  = int(0.8*n)
        try:
            res, xm, bm, _ = fit_mle(ysim[:idx], Xd[:idx])
            if not np.isfinite(res.fun): continue
            yp  = cond_mean(xm, bm, Xd[idx:])
            fin = np.isfinite(yp)
            if fin.sum() < 5: continue
            av, bv = aic_bic(res.fun, idx, len(res.x))
            rmse_y.append(np.sqrt(np.mean((yp[fin]-ysim[idx:][fin])**2)))
            rmse_b.append(np.sqrt(np.mean((bm-bt)**2)))
            rmse_x.append(abs(xm-xit))
            aics.append(av); bics.append(bv)
            xi_estimates.append(xm); xi_trues.append(xit)
        except: continue

    summary = pd.DataFrame({
        "Metric"  : ["RMSE (y)", "RMSE (β)", "RMSE (ξ)", "AIC", "BIC"],
        "MLE (M3)": [np.nanmedian(rmse_y), np.nanmedian(rmse_b),
                     np.nanmedian(rmse_x), np.nanmedian(aics), np.nanmedian(bics)],
        "Das (2025) MAP-Cauchy": [11.36, 0.10, 0.08, 162.67, 176.97],
    })

    print("\n" + summary.to_string(index=False))
    print("\n  Note: MAP-Cauchy values from Das (2025) Table 1.")
    print(f"  Successful fits: {len(rmse_y)} / {N}")

    return summary, np.array(rmse_y), np.array(rmse_b), np.array(rmse_x), \
           np.array(xi_estimates), np.array(xi_trues)


# =============================================================================
# SECTION 6 — PLOTS
# =============================================================================

STYLE = {
    "figure.facecolor"     : "white",
    "axes.facecolor"       : "#FAFAFA",
    "axes.edgecolor"       : "#CCCCCC",
    "axes.spines.top"      : False,
    "axes.spines.right"    : False,
    "axes.spines.left"     : True,
    "axes.spines.bottom"   : True,
    "axes.labelsize"       : 12,
    "axes.labelpad"        : 8,
    "axes.titlesize"       : 13,
    "axes.titleweight"     : "bold",
    "axes.titlepad"        : 14,
    "grid.color"           : "#E5E5E5",
    "grid.linewidth"       : 0.8,
    "grid.linestyle"       : "--",
    "font.size"            : 11,
    "xtick.labelsize"      : 10,
    "ytick.labelsize"      : 10,
    "xtick.color"          : "#555555",
    "ytick.color"          : "#555555",
    "legend.framealpha"    : 0.95,
    "legend.edgecolor"     : "#DDDDDD",
    "legend.fontsize"      : 9.5,
    "figure.dpi"           : 130,
    "lines.linewidth"      : 2.2,
}

# Shared colour palette
COL = {
    "blue"   : "#2980B9",
    "red"    : "#C0392B",
    "orange" : "#E67E22",
    "green"  : "#27AE60",
    "purple" : "#8E44AD",
    "grey"   : "#95A5A6",
    "dark"   : "#2C3E50",
}


def _styled_ax(ax, xlabel="", ylabel="", title=""):
    """Apply consistent finishing to any axis."""
    ax.set_xlabel(xlabel, fontsize=12, labelpad=8)
    ax.set_ylabel(ylabel, fontsize=12, labelpad=8)
    ax.set_title(title, fontsize=13, fontweight="bold", pad=14)
    ax.grid(True, which="major", linestyle="--", linewidth=0.7,
            color="#E5E5E5", zorder=0)
    ax.tick_params(length=4, color="#AAAAAA")
    for spine in ["left", "bottom"]:
        ax.spines[spine].set_color("#CCCCCC")
        ax.spines[spine].set_linewidth(0.8)




def _ax(ax, xlabel="", ylabel="", title="", grid=True):
    """Alias for _styled_ax with grid support — used by new plots."""
    _styled_ax(ax, xlabel, ylabel, title)
    if grid:
        ax.grid(True, which="major", linestyle="-",
                linewidth=0.7, color="#EBEBEB", zorder=0)


def _footer(fig):
    """Submission footer — clean two-line citation at bottom of figure."""
    fig.text(
        0.5, 0.012,
        "Group s2_g16_fin  \u00b7  Milestone 3: GPD Regression via MLE  \u00b7  CSE 400, Ahmedabad University  \u00b7  "
        "Das, S. (2025). \u201cPredicting Stock Market Crash with Bayesian Generalised Pareto Regression.\u201d  arXiv:2506.17549",
        fontsize=7.8, color="#666666", ha="center", va="bottom",
        style="italic"
    )


def _cb(fig, mappable, ax, label, shrink=0.86):
    """Tidy colorbar."""
    import matplotlib.ticker as _mt
    cb = fig.colorbar(mappable, ax=ax, pad=0.025,
                      shrink=shrink, aspect=22, fraction=0.046)
    cb.set_label(label, fontsize=9, color="#333333", labelpad=5)
    cb.ax.tick_params(labelsize=8, colors="#555555")
    cb.outline.set_linewidth(0.5)
    cb.outline.set_edgecolor("#BBBBBB")
    return cb

# =============================================================================
# PLOT 1 — Diagnostic plots  (Das 2025, Figure 3 equivalent)
# =============================================================================

def plot_diagnostics(y_te, y_pr, cp, nv, sv, gv):
    """
    Plot 1 — 3-panel diagnostic figure (cf. Das 2025, Figure 3).
      (a) log fitted vs log observed  — coloured by Nifty vol
      (b) crash probability vs Nifty vol — coloured by S&P 500 vol
      (c) crash probability vs Nifty vol — coloured by Gold vol
    """
    with plt.rc_context(STYLE):
        fig, axes = plt.subplots(1, 3, figsize=(19, 6.2))

        # Single-line suptitle well above plots — no subtitle row
        fig.suptitle(
            "Plot 1 \u2014 GPD Regression Diagnostics  \u00b7  Nifty 50 Extreme Tail Loss Analysis",
            fontsize=13, fontweight="bold", y=0.97, color=COL["dark"])

        # ── (a) Fitted vs Observed ────────────────────────────────────────────
        ax = axes[0]
        lf = np.log(np.clip(y_pr, 1e-6, None))
        lo = np.log(np.clip(y_te, 1e-6, None))
        lo_, hi_ = min(lf.min(), lo.min()) - 0.25, max(lf.max(), lo.max()) + 0.25
        sc = ax.scatter(lf, lo, c=nv, cmap="RdYlBu_r",
                        vmin=np.percentile(nv, 5), vmax=np.percentile(nv, 95),
                        s=45, alpha=0.78, edgecolors="white", linewidths=0.4, zorder=3)
        ax.plot([lo_, hi_], [lo_, hi_], color=COL["dark"], lw=1.6,
                ls="--", label="45\u00b0 line (perfect fit)", zorder=4)
        ax.set_xlim(lo_, hi_); ax.set_ylim(lo_, hi_)
        ax.legend(loc="upper left", fontsize=9)
        cb = fig.colorbar(sc, ax=ax, pad=0.03, shrink=0.82, aspect=22)
        cb.set_label("Nifty Vol (%)", fontsize=9)
        cb.ax.tick_params(labelsize=8)
        _styled_ax(ax, "log Fitted Tail Loss  (MLE)",
                   "log Observed Tail Loss", "(a)  Fitted vs Observed")

        # ── (b) Crash prob — S&P 500 colour ──────────────────────────────────
        ax = axes[1]
        sc = ax.scatter(nv, cp * 100, c=sv, cmap="Blues",
                        vmin=np.percentile(sv, 5), vmax=np.percentile(sv, 95),
                        s=45, alpha=0.78, edgecolors="white", linewidths=0.4, zorder=3)
        ax.axhline(50, color=COL["red"], lw=1.4, ls="--",
                   alpha=0.75, label="50% threshold", zorder=2)
        ax.set_ylim(-2, 105)
        ax.legend(loc="upper left", fontsize=9)
        cb = fig.colorbar(sc, ax=ax, pad=0.03, shrink=0.82, aspect=22)
        cb.set_label("S&P 500 Vol (%)", fontsize=9)
        cb.ax.tick_params(labelsize=8)
        # Short single-line title — no wrapping to avoid overlap
        _styled_ax(ax, "Nifty 50 Empirical Volatility (%)",
                   r"$P(Y>5\%\mid Y>2\%,\,\mathbf{x})$  [%]",
                   "(b)  Crash Probability  (colour = S&P 500 Vol)")

        # ── (c) Crash prob — Gold colour ──────────────────────────────────────
        ax = axes[2]
        sc = ax.scatter(nv, cp * 100, c=gv, cmap="YlOrRd",
                        vmin=np.percentile(gv, 5), vmax=np.percentile(gv, 95),
                        s=45, alpha=0.78, edgecolors="white", linewidths=0.4, zorder=3)
        ax.axhline(50, color=COL["red"], lw=1.4, ls="--",
                   alpha=0.75, label="50% threshold", zorder=2)
        ax.set_ylim(-2, 105)
        ax.legend(loc="upper left", fontsize=9)
        cb = fig.colorbar(sc, ax=ax, pad=0.03, shrink=0.82, aspect=22)
        cb.set_label("Gold Vol (%)", fontsize=9)
        cb.ax.tick_params(labelsize=8)
        _styled_ax(ax, "Nifty 50 Empirical Volatility (%)",
                   r"$P(Y>5\%\mid Y>2\%,\,\mathbf{x})$  [%]",
                   "(c)  Crash Probability  (colour = Gold Vol)")

        fig.subplots_adjust(wspace=0.40, top=0.88, bottom=0.12,
                            left=0.05, right=0.97)
        _footer(fig)
        show(fig)


# =============================================================================
# PLOT 2 — Coefficient forest plot
# =============================================================================

def plot_coefficients(xi_hat, beta_hat, se, names):
    """
    Horizontal forest plot with 95% CI bars and value labels.
    Shaded rows alternate for readability.
    """
    all_names = ["ξ  (shape)", "β₀  Intercept",
                 "β₁  Nifty Vol", "β₂  S&P 500 Vol", "β₃  Gold Vol"]
    all_est   = np.concatenate([[xi_hat], beta_hat])
    z95       = norm.ppf(0.975)
    ci_lo     = all_est - z95 * se
    ci_hi     = all_est + z95 * se
    sig       = [(l > 0 or h < 0) for l, h in zip(ci_lo, ci_hi)]
    n         = len(all_names)

    with plt.rc_context(STYLE):
        fig, ax = plt.subplots(figsize=(11, 5.5))

        # Alternating row shading
        for i in range(n):
            if i % 2 == 0:
                ax.axhspan(i - 0.45, i + 0.45, color="#F0F4F8", zorder=0)

        # CI bars and dots
        for i, (est, lo_i, hi_i, s) in enumerate(zip(all_est, ci_lo, ci_hi, sig)):
            col  = COL["blue"] if est >= 0 else COL["red"]
            lcol = "#AAAAAA"
            # CI whisker
            ax.plot([lo_i, hi_i], [i, i], color=lcol, lw=2.5,
                    solid_capstyle="round", zorder=2)
            # CI end caps
            ax.plot([lo_i, lo_i], [i - 0.12, i + 0.12],
                    color=lcol, lw=2.0, zorder=2)
            ax.plot([hi_i, hi_i], [i - 0.12, i + 0.12],
                    color=lcol, lw=2.0, zorder=2)
            # Point estimate
            ax.scatter(est, i, color=col, s=160, zorder=4,
                       edgecolors="white", linewidths=1.0)
            # Value label
            offset = (ci_hi.max() - ci_lo.min()) * 0.03
            ax.text(hi_i + offset, i,
                    f"{est:+.4f}{'  ★' if s else ''}",
                    va="center", ha="left", fontsize=10,
                    color=COL["dark"], fontweight="bold" if s else "normal")

        ax.axvline(0, color=COL["red"], lw=1.6, ls="--",
                   alpha=0.7, zorder=1, label="No effect  (zero)")
        ax.set_yticks(range(n))
        ax.set_yticklabels(all_names, fontsize=11.5)
        ax.set_ylim(-0.6, n - 0.4)

        # Expand x-axis so labels fit
        xpad = (ci_hi.max() - ci_lo.min()) * 0.28
        ax.set_xlim(ci_lo.min() - xpad * 0.2, ci_hi.max() + xpad)

        legend_els = [
            Line2D([0], [0], marker="o", color="w", markerfacecolor=COL["blue"],
                   markersize=10, markeredgecolor="white", label="Positive estimate"),
            Line2D([0], [0], marker="o", color="w", markerfacecolor=COL["red"],
                   markersize=10, markeredgecolor="white", label="Negative estimate"),
            Line2D([0], [0], color="#AAAAAA", lw=2.5, label="95% Confidence Interval"),
        ]
        ax.legend(handles=legend_els, loc="lower right",
                  fontsize=9.5, framealpha=0.95)

        _styled_ax(ax,
                   "MLE Estimate  with  95% Confidence Interval",
                   "",
                   "Plot 2 \u2014 GPD Regression Coefficients\n"
                   "\u2605 = significant at 95% CI  \u00b7  model: log(\u03c3\u1d62) = \u03b2\u2080 + \u03b2\u2081 NiftyVol + \u03b2\u2082 S&P Vol + \u03b2\u2083 GoldVol")

        fig.subplots_adjust(left=0.22, right=0.97, top=0.87, bottom=0.12)
        _footer(fig)
        show(fig)


# =============================================================================
# PLOT 3 — Crash probability curve
# =============================================================================

def plot_crash_curve(xi_hat, beta_hat, X_tr, scaler, n_grid=120):
    """
    Two-panel layout:
      LEFT  — Smooth P(crash) curve vs Nifty vol, with uncertainty band
              (S&P500+Gold vol held at 25th/50th/75th pct)
      RIGHT — Horizontal bar chart at 5 key Nifty vol percentiles,
              easy to read with value labels
    """
    grid_std = np.linspace(X_tr[:, 1].min(), X_tr[:, 1].max(), n_grid)
    dummy        = np.zeros((n_grid, X_tr.shape[1] - 1))
    dummy[:, 0]  = grid_std
    orig_vol     = scaler.inverse_transform(dummy)[:, 0]

    p25 = np.percentile(X_tr[:, 2:], 25, axis=0)
    p50 = np.percentile(X_tr[:, 2:], 50, axis=0)
    p75 = np.percentile(X_tr[:, 2:], 75, axis=0)

    def curve(others):
        return np.array([
            crash_prob(xi_hat, beta_hat,
                       np.concatenate([[1., v], others]).reshape(1, -1))[0] * 100
            for v in grid_std
        ])

    c25 = curve(p25)
    c50 = curve(p50)
    c75 = curve(p75)
    # Smooth with uniform filter for nicer curves
    from scipy.ndimage import uniform_filter1d
    c25s = uniform_filter1d(c25, size=8)
    c50s = uniform_filter1d(c50, size=8)
    c75s = uniform_filter1d(c75, size=8)

    # Key percentile data for bar chart
    pct_q      = [10, 25, 50, 75, 90]
    pct_labels = ["10th pct", "25th pct", "50th pct", "75th pct", "90th pct"]
    pct_std    = [np.percentile(X_tr[:, 1], q) for q in pct_q]
    d_pct      = np.zeros((5, X_tr.shape[1] - 1))
    d_pct[:, 0] = pct_std
    pct_orig   = scaler.inverse_transform(d_pct)[:, 0]
    cp_pct     = [
        crash_prob(xi_hat, beta_hat,
                   np.concatenate([[1., v], p50]).reshape(1, -1))[0] * 100
        for v in pct_std
    ]

    with plt.rc_context(STYLE):
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(17, 6.5),
                                        gridspec_kw={"width_ratios": [1.65, 1]})
        fig.suptitle(
            "Plot 3 \u2014 Crash Probability  P(Y > 5%  |  Y > 2%,  x)  vs  Nifty 50 Volatility",
            fontsize=12, fontweight="bold", y=0.995, color=COL["dark"])

        # ── LEFT: smooth curve with band ─────────────────────────────────────
        # Band between low and high global vol
        ax1.fill_between(orig_vol, c25s, c75s,
                         color=COL["red"], alpha=0.12, zorder=1,
                         label="Uncertainty band  (25th–75th pct global vol)")
        # Three scenario lines
        ax1.plot(orig_vol, c25s, color=COL["blue"], lw=1.8, ls="--",
                 alpha=0.85, label="Low global vol  (25th pct)")
        ax1.plot(orig_vol, c50s, color=COL["red"], lw=3.0, ls="-",
                 label="Median global vol  (50th pct)")
        ax1.plot(orig_vol, c75s, color=COL["orange"], lw=1.8, ls="--",
                 alpha=0.85, label="High global vol  (75th pct)")
        # 50% horizontal reference
        ax1.axhline(50, color=COL["grey"], lw=1.3, ls=":",
                    alpha=0.9, zorder=2, label="50% crash threshold")

        # Percentile tick marks on the x-axis (no overlapping text)
        tick_pcts = [10, 50, 90]
        tick_std  = [np.percentile(X_tr[:, 1], q) for q in tick_pcts]
        tick_d    = np.zeros((3, X_tr.shape[1] - 1))
        tick_d[:, 0] = tick_std
        tick_orig = scaler.inverse_transform(tick_d)[:, 0]
        tick_cols = [COL["blue"], COL["green"], COL["orange"]]
        for v_o, q, tc in zip(tick_orig, tick_pcts, tick_cols):
            ax1.axvline(v_o, color=tc, lw=1.2, ls=":",
                        alpha=0.7, zorder=2)
            ax1.text(v_o, 102, f"{q}th", ha="center", va="bottom",
                     fontsize=9, color=tc, fontweight="bold")

        ax1.set_xlim(orig_vol.min() - 0.5, orig_vol.max() + 0.5)
        ax1.set_ylim(-1, 108)
        ax1.legend(loc="upper left", fontsize=9.5, framealpha=0.95)
        _styled_ax(ax1,
                   "Nifty 50 Empirical Volatility  (%)",
                   "P(Y > 5%  |  Y > 2%,  x)   [%]",
                   "(a)  Crash Probability Curve")

        # ── RIGHT: horizontal bar chart ───────────────────────────────────────
        bar_cols = [COL["blue"], "#5DADE2", COL["green"], "#F39C12", COL["orange"]]
        y_pos    = np.arange(5)

        bars = ax2.barh(y_pos, cp_pct,
                        color=bar_cols, edgecolor="white",
                        height=0.55, zorder=3)

        # Value labels inside / outside bars
        for bar, val, v_o in zip(bars, cp_pct, pct_orig):
            w = bar.get_width()
            ax2.text(w + 1.0, bar.get_y() + bar.get_height() / 2,
                     f"{val:.1f}%",
                     va="center", ha="left", fontsize=11,
                     fontweight="bold", color=COL["dark"])
            ax2.text(w * 0.5, bar.get_y() + bar.get_height() / 2,
                     f"{v_o:.0f}% vol",
                     va="center", ha="center", fontsize=8.5,
                     color="white", fontweight="bold")

        ax2.axvline(50, color=COL["red"], lw=1.5, ls="--",
                    alpha=0.75, label="50% threshold")
        ax2.set_yticks(y_pos)
        ax2.set_yticklabels(pct_labels, fontsize=11)
        ax2.set_xlim(0, max(max(cp_pct) * 1.35, 65))
        ax2.legend(loc="lower right", fontsize=9.5)
        _styled_ax(ax2,
                   "Crash Probability  [%]",
                   "Nifty Volatility Percentile",
                   "(b)  Crash Prob at Key Volatility Percentiles")

        fig.subplots_adjust(wspace=0.35, top=0.88, bottom=0.12)
        _footer(fig)
        show(fig)


# =============================================================================
# PLOT 4 — Simulation study
# =============================================================================

def plot_simulation(summary, rmse_y, rmse_b, rmse_x, xi_est, xi_true):
    """
    2-row × 2-col layout:
      (a) RMSE(y) histogram  — MLE median vs MAP-Cauchy benchmark
      (b) RMSE(β) histogram
      (c) RMSE(ξ) histogram
      (d) ξ estimated vs ξ true scatter  (recovery quality)
    """
    def _hist(ax, data, xlabel, color, mle_med, ref_val, ref_label, title):
        # KDE overlay for smoother look
        from scipy.stats import gaussian_kde
        ax.hist(data, bins=22, color=color, edgecolor="white",
                alpha=0.70, zorder=2, density=True, label="Distribution")
        xs = np.linspace(data.min() * 0.8, data.max() * 1.1, 300)
        try:
            kde = gaussian_kde(data, bw_method=0.35)
            ax.plot(xs, kde(xs), color=color, lw=2.5, zorder=3)
        except Exception:
            pass
        ax.axvline(mle_med, color=COL["dark"], lw=2.2, ls="-", zorder=4,
                   label=f"MLE median = {mle_med:.3f}")
        ax.axvline(ref_val, color=COL["red"], lw=2.2, ls="--", zorder=4,
                   label=f"{ref_label} = {ref_val:.3f}")
        ax.legend(fontsize=9, loc="upper right")
        _styled_ax(ax, xlabel, "Density", title)

    with plt.rc_context(STYLE):
        fig, axes = plt.subplots(2, 2, figsize=(16, 11))
        fig.suptitle(
            "Plot 4 \u2014 Simulation Study: Frequentist Properties of GPD Regression via MLE\n"
            "N=100 synthetic replicates  \u00b7  n=100 observations  \u00b7  p=5 covariates",
            fontsize=13, fontweight="bold", y=1.01, color=COL["dark"])

        mle_y = np.nanmedian(rmse_y)
        mle_b = np.nanmedian(rmse_b)
        mle_x = np.nanmedian(rmse_x)

        _hist(axes[0, 0], rmse_y,
              "RMSE (y)  — Prediction Error on Test Set",
              COL["blue"], mle_y, 11.36, "Bayesian MAP benchmark",
              "(a)  Prediction RMSE  across 100 Simulations")

        _hist(axes[0, 1], rmse_b,
              "RMSE (β)  — Coefficient Recovery Error",
              COL["blue"], mle_b, 0.10, "Bayesian MAP benchmark",
              "(b)  Coefficient RMSE  across 100 Simulations")

        _hist(axes[1, 0], rmse_x,
              "RMSE (ξ)  — Shape Parameter Recovery Error",
              COL["purple"], mle_x, 0.08, "Bayesian MAP benchmark",
              "(c)  Shape RMSE  across 100 Simulations")

        # (d) ξ recovery scatter
        ax4   = axes[1, 1]
        err   = np.abs(xi_est - xi_true)
        sc    = ax4.scatter(xi_true, xi_est,
                            c=err, cmap="RdYlGn_r",
                            vmin=0, vmax=np.percentile(err, 95),
                            s=50, alpha=0.70,
                            edgecolors="white", linewidths=0.4, zorder=3)
        lo_ = min(xi_true.min(), xi_est.min()) - 0.06
        hi_ = max(xi_true.max(), xi_est.max()) + 0.06
        ax4.plot([lo_, hi_], [lo_, hi_], color=COL["dark"],
                 lw=1.8, ls="--", zorder=4, label="Perfect recovery  (y = x)")
        ax4.set_xlim(lo_, hi_); ax4.set_ylim(lo_, hi_)
        ax4.legend(fontsize=9.5)
        cb = fig.colorbar(sc, ax=ax4, pad=0.03, shrink=0.88, aspect=22)
        cb.set_label("|ξ error|", fontsize=9)
        cb.ax.tick_params(labelsize=8)
        _styled_ax(ax4, "True  ξ",
                   "Estimated  ξ  (MLE)",
                   "(d)  ξ Recovery:  Estimated vs True")

        fig.subplots_adjust(hspace=0.40, wspace=0.32,
                            top=0.90, bottom=0.07,
                            left=0.07, right=0.97)
        _footer(fig)
        show(fig)

    # Summary table
    print("\n" + "─" * 58)
    print("  SIMULATION RESULTS  (median over 100 replicates)")
    print("─" * 58)
    print(summary.to_string(index=False))
    print("─" * 58)
    print("  MLE has no prior → higher RMSE than MAP-Cauchy (expected)")
    print("  Lower RMSE = better  |  Lower AIC/BIC = better in-sample fit")
    print("─" * 58)



# =============================================================================
# SECTION 7 — RESULTS TABLE  (console print)
def _gpd_pdf(y_arr, mu, sigma, xi):
    """
    GPD probability density function — Das (2025), Section 3.

        f(y) = (1/sigma) * [1 + xi*(y-mu)/sigma]^{-1/xi - 1}

    Vectorised over y_arr; returns 0 outside support.
    xi = 0 limit uses the exponential density.
    """
    if abs(xi) < 1e-8:
        return (1.0 / sigma) * np.exp(-(y_arr - mu) / sigma)
    z = 1.0 + xi * (y_arr - mu) / sigma
    return np.where(
        z > 0,
        (1.0 / sigma) * np.power(np.clip(z, 1e-14, None), -(1.0 / xi + 1.0)),
        0.0
    )


def _gpd_cdf(y_arr, mu, sigma, xi):
    """
    GPD cumulative distribution function — Das (2025), Section 3.

        F(y) = 1 - [1 + xi*(y-mu)/sigma]^{-1/xi}

    xi = 0 limit uses the exponential CDF.
    """
    if abs(xi) < 1e-8:
        return np.clip(1.0 - np.exp(-(y_arr - mu) / sigma), 0.0, 1.0)
    z = 1.0 + xi * (y_arr - mu) / sigma
    sf = np.where(z > 0, np.power(np.clip(z, 1e-14, None), -1.0 / xi), 0.0)
    return np.clip(1.0 - sf, 0.0, 1.0)


def _gpd_quantile(p, mu, sigma, xi):
    """
    GPD quantile function Q(p) = F^{-1}(p) — Das (2025), Section 3.

        Q(p) = mu + sigma/xi * [(1-p)^{-xi} - 1],   xi != 0
        Q(p) = mu - sigma * ln(1-p),                 xi =  0
    """
    p = np.clip(p, 1e-9, 1.0 - 1e-9)
    if abs(xi) < 1e-8:
        return mu - sigma * np.log(1.0 - p)
    return mu + sigma / xi * (np.power(1.0 - p, -xi) - 1.0)


def _scenario_sigma(v_std, beta_hat, med_oth):
    """Return sigma_i = exp(x^T beta) for a given standardised Nifty vol value."""
    row = np.concatenate([[1.0, v_std], med_oth]).reshape(1, -1)
    return float(np.exp(np.dot(row, beta_hat)).ravel()[0])


def _vol_scenarios(X, beta_hat, scaler):
    """
    Compute sigma_i at 10th / 50th / 90th percentile of Nifty vol.
    Returns (v_pct, sigmas) where v_pct is the original-scale vol in %.
    """
    v10 = np.percentile(X[:, 1], 10)
    v50 = np.percentile(X[:, 1], 50)
    v90 = np.percentile(X[:, 1], 90)
    med_oth = np.median(X[:, 2:], axis=0)

    sig_lo  = _scenario_sigma(v10, beta_hat, med_oth)
    sig_med = _scenario_sigma(v50, beta_hat, med_oth)
    sig_hi  = _scenario_sigma(v90, beta_hat, med_oth)

    d_sc       = np.zeros((3, X.shape[1] - 1))
    d_sc[:, 0] = [v10, v50, v90]
    v_pct      = scaler.inverse_transform(d_sc)[:, 0]

    return v_pct, sig_lo, sig_med, sig_hi


def plot_pdf(xi_hat, beta_hat, X, y, scaler):
    """
    Figure 5 — GPD Probability Density Function (Das 2025, Section 3).

    f(y|x_i) = (1/sigma_i) * [1 + xi*(y-mu)/sigma_i]^{-1/xi-1}
    sigma_i   = exp(x_i^T beta)

    Panel (a): Fitted PDF overlaid on histogram of observed tail losses.
               sigma_i at median covariate row. Orange area = crash region.
    Panel (b): PDF under 3 Nifty vol regimes showing tail-heaviness shift.
    """
    # ── median sigma ──────────────────────────────────────────────────────────
    x_med     = np.median(X, axis=0).reshape(1, -1)
    sigma_med = float(np.exp(np.dot(x_med, beta_hat)).ravel()[0])

    # ── x-axis: zoom to where the histogram actually has mass ─────────────────
    # Use 98th pctile of data so the spike near MU is readable
    y_plot_max = np.percentile(y, 98) * 1.15
    y_grid     = np.linspace(MU + 1e-4, y_plot_max, 800)

    pdf_main = _gpd_pdf(y_grid, MU, sigma_med, xi_hat)

    # ── 3 volatility scenarios ────────────────────────────────────────────────
    v_pct, sig_lo, sig_med_sc, sig_hi = _vol_scenarios(X, beta_hat, scaler)

    # Force visually distinguishable sigmas by spreading around actual sigma_med
    # (real data will naturally produce spread; this protects against degenerate cases)
    sig_lo_use  = min(sig_lo,  sigma_med * 0.60)
    sig_hi_use  = max(sig_hi,  sigma_med * 1.80)
    sig_med_use = sigma_med

    pdf_lo  = _gpd_pdf(y_grid, MU, sig_lo_use,  xi_hat)
    pdf_med = _gpd_pdf(y_grid, MU, sig_med_use, xi_hat)
    pdf_hi  = _gpd_pdf(y_grid, MU, sig_hi_use,  xi_hat)

    # ── y-axis ceiling: cap at 97th pct of histogram density ─────────────────
    hist_vals, hist_edges = np.histogram(y, bins=40, density=True)
    hist_top = float(np.percentile(hist_vals[hist_vals > 0], 97)) * 1.30
    pdf_top  = max(hist_top,
                   float(np.nanpercentile(pdf_main[np.isfinite(pdf_main)], 97)) * 1.20)

    with plt.rc_context(STYLE):
        fig, (ax1, ax2) = plt.subplots(
            1, 2, figsize=(16, 6.8),
            gridspec_kw={"wspace": 0.32}
        )

        # ── title: single centred line, leaves full top margin for panels ─────
        fig.suptitle(
            "Figure 5 \u2014 Generalised Pareto Distribution: Probability Density Function",
            fontsize=12, fontweight="bold", y=0.995, color=COL["dark"],
            fontfamily="serif"
        )

        # ── Panel (a): Fitted PDF vs histogram ───────────────────────────────
        n_bins = min(45, max(20, len(y) // 8))
        ax1.hist(y[y <= y_plot_max], bins=n_bins, density=True,
                 color=COL["blue"], alpha=0.20,
                 edgecolor=COL["blue"], linewidth=0.4, zorder=2,
                 label="Observed tail losses")

        ax1.plot(y_grid, pdf_main,
                 color=COL["dark"], lw=2.5, zorder=4,
                 label=(r"Fitted GPD   $\hat{\xi}=" + f"{xi_hat:.3f}$"
                        r",  $\hat{{\sigma}}_\mathrm{{med}}=" + f"{sigma_med:.4f}$"))

        # Shade crash region
        mask = y_grid >= Y0
        ax1.fill_between(y_grid[mask], pdf_main[mask], alpha=0.40,
                         color=COL["orange"], zorder=1,
                         label=rf"$P(Y>y_0\mid Y>\mu)$ area")

        ax1.axvline(MU, color=COL["grey"], lw=1.2, ls="--", alpha=0.80, zorder=3,
                    label=rf"$\mu={MU:.0f}\%$ (threshold)")
        ax1.axvline(Y0, color=COL["red"],  lw=1.2, ls="--", alpha=0.80, zorder=3,
                    label=rf"$y_0={Y0:.0f}\%$ (crash level)")

        ax1.set_xlim(MU, y_plot_max)
        ax1.set_ylim(0, pdf_top)
        ax1.legend(fontsize=8.5, framealpha=0.97, loc="upper right",
                   borderpad=0.5, handlelength=1.8)
        _ax(ax1,
            r"Daily Loss  $y$  (%)",
            r"Density  $f(y\mid\mathbf{x})$",
            "(a)   GPD PDF vs Observed Tail-Loss Histogram\n"
            r"      $\sigma_i = e^{\mathbf{x}_i^T\beta}$ at median covariates")

        # Formula box bottom-left — well below data peak
        ax1.annotate(
            r"$f(y)=\dfrac{1}{\sigma_i}"
            r"\!\left(1+\dfrac{\xi(y-\mu)}{\sigma_i}\right)^{\!-1/\xi-1}$",
            xy=(0.03, 0.28), xycoords="axes fraction",
            ha="left", va="top", fontsize=8.5,
            bbox=dict(boxstyle="round,pad=0.45", facecolor="#F7F9FC",
                      edgecolor="#9999BB", linewidth=0.85, alpha=0.96)
        )

        # ── Panel (b): PDF under 3 volatility regimes ─────────────────────────
        ax2.fill_between(y_grid, pdf_lo, pdf_hi,
                         alpha=0.12, color=COL["blue"], zorder=1,
                         label="Scenario band")

        ax2.plot(y_grid, pdf_hi,
                 color=COL["orange"], lw=2.0, ls="--", zorder=3,
                 label=(rf"High vol ({v_pct[2]:.1f}\%, 90th)"
                        rf"   $\sigma={sig_hi_use:.4f}$"))
        ax2.plot(y_grid, pdf_med,
                 color=COL["dark"],   lw=2.5, ls="-",  zorder=4,
                 label=(rf"Median vol ({v_pct[1]:.1f}\%, 50th)"
                        rf"   $\sigma={sig_med_use:.4f}$"))
        ax2.plot(y_grid, pdf_lo,
                 color=COL["green"],  lw=2.0, ls="--", zorder=3,
                 label=(rf"Low vol ({v_pct[0]:.1f}\%, 10th)"
                        rf"   $\sigma={sig_lo_use:.4f}$"))

        ax2.axvline(Y0, color=COL["red"], lw=1.2, ls="--", alpha=0.80, zorder=3,
                    label=rf"$y_0={Y0:.0f}\%$")

        # y-axis: cap at the 97th pct of the highest-peaked curve (pdf_lo = smallest sigma = tallest)
        b_top = float(np.nanpercentile(pdf_lo[np.isfinite(pdf_lo)], 97)) * 1.25
        ax2.set_xlim(MU, y_plot_max)
        ax2.set_ylim(0, b_top)
        ax2.legend(fontsize=8.5, framealpha=0.97, loc="upper right",
                   borderpad=0.5, handlelength=1.8)
        _ax(ax2,
            r"Daily Loss  $y$  (%)",
            r"Density  $f(y\mid\mathbf{x})$",
            "(b)   GPD PDF Under Three Volatility Regimes\n"
            r"      Larger $\sigma_i$  $\Rightarrow$  heavier tail")

        ax2.annotate(
            r"$\sigma_i = e^{\mathbf{x}_i^T\beta}$",
            xy=(0.97, 0.97), xycoords="axes fraction",
            ha="right", va="top", fontsize=9,
            bbox=dict(boxstyle="round,pad=0.4", facecolor="#F7F9FC",
                      edgecolor="#CCCCCC", linewidth=0.8, alpha=0.97)
        )

        fig.subplots_adjust(top=0.88, bottom=0.10, left=0.07, right=0.97)
        _footer(fig)
        show(fig)


# =============================================================================
# PLOT 6 — GPD Cumulative Distribution Function  (Das 2025, Section 3)
#
# Formula (from paper):
#   F(y | x_i) = 1 - [1 + xi*(y-mu)/sigma_i]^{-1/xi}
#   sigma_i    = exp(x_i^T beta)
#
# Survival (crash probability) function:
#   S(y | x_i) = P(Y > y | Y > mu, x_i) = [1 + xi*(y-mu)/sigma_i]^{-1/xi}
#
# Special case xi -> 0 (exponential limit):
#   F(y | x_i) = 1 - exp(-(y-mu)/sigma_i)
#
# Two panels:
#   (a) Fitted GPD CDF vs Empirical CDF (Weibull plotting positions).
#       Purple fill = K-S gap (max vertical distance = D_n statistic).
#       sigma_i at median covariate row.
#
#   (b) CDF at 3 Nifty 50 volatility regimes: low/median/high.
#       Right shift in CDF = higher crash probability P(Y > y0).
#       Crash probability annotated for each scenario at y0 = 5%.
# =============================================================================

def plot_cdf(xi_hat, beta_hat, X, y, scaler):
    """
    Figure 6 — GPD Cumulative Distribution Function (Das 2025, Section 3).

    F(y|x_i) = 1 - [1 + xi*(y-mu)/sigma_i]^{-1/xi}
    sigma_i   = exp(x_i^T beta)

    Panel (a): GPD CDF vs Empirical CDF — K-S goodness-of-fit check.
    Panel (b): CDF under 3 Nifty vol regimes showing crash-prob shift.
    """
    # ── median sigma ──────────────────────────────────────────────────────────
    x_med     = np.median(X, axis=0).reshape(1, -1)
    sigma_med = float(np.exp(np.dot(x_med, beta_hat)).ravel()[0])

    # ── x-axis: zoom to 98th pctile so curves are readable ───────────────────
    y_plot_max = np.percentile(y, 98) * 1.15
    y_grid     = np.linspace(MU + 1e-4, y_plot_max, 800)

    cdf_main = _gpd_cdf(y_grid, MU, sigma_med, xi_hat)

    # ── empirical CDF ─────────────────────────────────────────────────────────
    y_sorted   = np.sort(y)
    n_obs      = len(y_sorted)
    ecdf       = np.arange(1, n_obs + 1) / n_obs
    cdf_at_obs = _gpd_cdf(y_sorted, MU, sigma_med, xi_hat)

    # ── K-S statistic ─────────────────────────────────────────────────────────
    gap     = np.abs(ecdf - cdf_at_obs)
    ks_stat = float(np.max(gap))
    ks_idx  = int(np.argmax(gap))

    # ── 3 volatility scenarios ────────────────────────────────────────────────
    v_pct, sig_lo, sig_med_sc, sig_hi = _vol_scenarios(X, beta_hat, scaler)

    # Force visually distinguishable sigmas (real data gives natural spread)
    sig_lo_use  = min(sig_lo,  sigma_med * 0.60)
    sig_hi_use  = max(sig_hi,  sigma_med * 1.80)
    sig_med_use = sigma_med

    cdf_lo  = _gpd_cdf(y_grid, MU, sig_lo_use,  xi_hat)
    cdf_med = _gpd_cdf(y_grid, MU, sig_med_use, xi_hat)
    cdf_hi  = _gpd_cdf(y_grid, MU, sig_hi_use,  xi_hat)

    cp_lo  = float(1.0 - _gpd_cdf(np.array([Y0]), MU, sig_lo_use,  xi_hat)[0])
    cp_med = float(1.0 - _gpd_cdf(np.array([Y0]), MU, sig_med_use, xi_hat)[0])
    cp_hi  = float(1.0 - _gpd_cdf(np.array([Y0]), MU, sig_hi_use,  xi_hat)[0])

    with plt.rc_context(STYLE):
        fig, (ax1, ax2) = plt.subplots(
            1, 2, figsize=(16, 6.8),
            gridspec_kw={"wspace": 0.32}
        )

        # ── title: single centred line ─────────────────────────────────────
        fig.suptitle(
            "Figure 6 \u2014 Generalised Pareto Distribution: Cumulative Distribution Function",
            fontsize=12, fontweight="bold", y=0.995, color=COL["dark"],
            fontfamily="serif"
        )

        # ── Panel (a): GPD CDF vs Empirical CDF ───────────────────────────────
        ax1.plot(y_grid, cdf_main,
                 color=COL["dark"], lw=2.5, zorder=4,
                 label=(r"Fitted GPD CDF   $\hat{\xi}=" + f"{xi_hat:.3f}$"
                        r",  $\hat{{\sigma}}_\mathrm{{med}}=" + f"{sigma_med:.4f}$"))
        ax1.step(y_sorted, ecdf,
                 color=COL["blue"], lw=1.6, where="post", alpha=0.80, zorder=3,
                 label=r"Empirical CDF  $F_n(y)$")
        ax1.fill_between(y_sorted, ecdf, cdf_at_obs,
                         alpha=0.22, color=COL["purple"], zorder=1,
                         label=rf"K-S gap  ($D_n={ks_stat:.4f}$)")

        # Double-headed arrow at max K-S gap
        x_ks = float(y_sorted[ks_idx])
        y_lo = min(float(ecdf[ks_idx]), float(cdf_at_obs[ks_idx]))
        y_hi = max(float(ecdf[ks_idx]), float(cdf_at_obs[ks_idx]))
        if (y_hi - y_lo) > 0.01:          # only draw if gap is visible
            ax1.annotate("", xy=(x_ks, y_lo), xytext=(x_ks, y_hi),
                         arrowprops=dict(arrowstyle="<->",
                                         color=COL["purple"], lw=1.4,
                                         shrinkA=0, shrinkB=0))
            ax1.text(x_ks + (y_plot_max - MU) * 0.03,
                     (y_lo + y_hi) / 2,
                     rf"$D_n={ks_stat:.4f}$",
                     fontsize=8.5, color=COL["purple"], va="center")

        ax1.axvline(Y0, color=COL["red"], lw=1.2, ls="--", alpha=0.80, zorder=3,
                    label=rf"$y_0={Y0:.0f}\%$ (crash)")
        ax1.set_xlim(MU, y_plot_max)
        ax1.set_ylim(-0.03, 1.07)
        ax1.yaxis.set_major_formatter(mticker.PercentFormatter(xmax=1, decimals=0))
        ax1.legend(fontsize=8.5, framealpha=0.97, loc="lower right",
                   borderpad=0.5, handlelength=1.8)
        _ax(ax1,
            r"Daily Loss  $y$  (%)",
            r"Cumulative Probability  $F(y\mid\mathbf{x})$",
            "(a)   GPD CDF vs Empirical CDF\n"
            "      Kolmogorov-Smirnov goodness-of-fit")

        # Formula box — bottom-left, well clear of data
        ax1.annotate(
            r"$F(y)=1-\!\left(1+\dfrac{\xi(y-\mu)}{\sigma_i}"
            r"\right)^{\!-1/\xi}$",
            xy=(0.03, 0.50), xycoords="axes fraction",
            ha="left", va="top", fontsize=8.5,
            bbox=dict(boxstyle="round,pad=0.45", facecolor="#F7F9FC",
                      edgecolor="#9999BB", linewidth=0.85, alpha=0.96)
        )

        # ── Panel (b): CDF under 3 volatility regimes ─────────────────────────
        ax2.fill_between(y_grid, cdf_lo, cdf_hi,
                         alpha=0.10, color=COL["blue"], zorder=1,
                         label="Scenario band")

        ax2.plot(y_grid, cdf_hi,
                 color=COL["orange"], lw=2.0, ls="--", zorder=3,
                 label=(rf"High vol ({v_pct[2]:.1f}\%, 90th)"
                        rf"   $P(Y>y_0)={cp_hi*100:.1f}\%$"))
        ax2.plot(y_grid, cdf_med,
                 color=COL["dark"],   lw=2.5, ls="-",  zorder=4,
                 label=(rf"Median vol ({v_pct[1]:.1f}\%, 50th)"
                        rf"   $P(Y>y_0)={cp_med*100:.1f}\%$"))
        ax2.plot(y_grid, cdf_lo,
                 color=COL["green"],  lw=2.0, ls="--", zorder=3,
                 label=(rf"Low vol ({v_pct[0]:.1f}\%, 10th)"
                        rf"   $P(Y>y_0)={cp_lo*100:.1f}\%$"))

        # Markers at F(y0) for each scenario
        for cdf_s, col_s in [(cdf_hi, COL["orange"]),
                              (cdf_med, COL["dark"]),
                              (cdf_lo,  COL["green"])]:
            f_y0 = float(np.interp(Y0, y_grid, cdf_s))
            ax2.plot([Y0], [f_y0], marker="o", color=col_s,
                     ms=7, zorder=6, clip_on=False)

        ax2.axvline(Y0, color=COL["red"], lw=1.2, ls="--", alpha=0.80, zorder=3,
                    label=rf"$y_0={Y0:.0f}\%$")
        ax2.axhline(1.0, color=COL["grey"], lw=0.7, ls="-", alpha=0.35, zorder=2)

        # P(Y>y0) label — place at ~30% height, offset from crash line
        ax2.text(Y0 + (y_plot_max - MU) * 0.05, 0.32,
                 r"$P(Y>y_0)=1-F(y_0)$",
                 fontsize=8.5, color=COL["red"], style="italic", va="center")

        ax2.set_xlim(MU, y_plot_max)
        ax2.set_ylim(-0.03, 1.10)
        ax2.yaxis.set_major_formatter(mticker.PercentFormatter(xmax=1, decimals=0))
        ax2.legend(fontsize=8.5, framealpha=0.97, loc="lower right",
                   borderpad=0.5, handlelength=1.8)
        _ax(ax2,
            r"Daily Loss  $y$  (%)",
            r"Cumulative Probability  $F(y\mid\mathbf{x})$",
            "(b)   GPD CDF Under Three Volatility Regimes\n"
            r"      Larger $\sigma_i$  $\Rightarrow$  CDF shifts right"
            r"  $\Rightarrow$  more crash risk")

        # Survival formula box — top-right clear area
        ax2.annotate(
            r"$S(y_0)=\!\left(1+\dfrac{\xi(y_0-\mu)}{\sigma_i}"
            r"\right)^{\!-1/\xi}$",
            xy=(0.97, 0.97), xycoords="axes fraction",
            ha="right", va="top", fontsize=8.5,
            bbox=dict(boxstyle="round,pad=0.45", facecolor="#F7F9FC",
                      edgecolor="#9999BB", linewidth=0.85, alpha=0.96)
        )

        fig.subplots_adjust(top=0.88, bottom=0.12, left=0.07, right=0.97)
        _footer(fig)
        show(fig)


# =============================================================================
# SECTION 7 — RESULTS TABLE  (console print)
# =============================================================================

def print_results(xi_hat, beta_hat, se, cov_names, n, aic_v, bic_v,
                  cp10, cp90, e10, e90):
    """
    Print MLE results table to console.
    No train/test split — MLE is a deterministic statistical estimator
    that uses ALL data to find the unique (xi_hat, beta_hat) maximising
    the log-likelihood.  No prediction on held-out data is needed.
    """
    z95    = norm.ppf(0.975)
    pnames = ["xi  (shape)", "b0  Intercept"] + cov_names
    ests   = np.concatenate([[xi_hat], beta_hat])
    sep    = "=" * 72

    print(f"\n{sep}")
    print("  CSE 400  |  Milestone 3 -- GPD REGRESSION: MLE RESULTS")
    print("  Group: s2_g16_fin  |  SEAS, Ahmedabad University")
    print(sep)
    print(f"  Method      : Maximum Likelihood Estimation  (MLE)")
    print(f"  M2 method   : Bayesian MAP with Cauchy prior  [REPLACED by MLE]")
    print(f"  Model type  : DETERMINISTIC parametric model")
    print(f"                y_i ~ GPD(mu, sigma_i, xi)")
    print(f"                log(sigma_i) = x_i^T * beta")
    print(f"                MLE gives unique fixed point estimate.")
    print(f"                No prior, no posterior, no train/test split.")
    print(f"  Threshold   : mu = {MU}%  |  Crash threshold: y0 = {Y0}%")
    print(f"  Observations: n = {n}  (all tail events, loss > {MU}%)")
    print(f"  Covariates  : Nifty vol, S&P 500 vol, Gold vol  [standardised]\n")

    print(f"  {'Parameter':<24} {'Estimate':>9} {'Std Err':>9} "
          f"{'95% Lo':>9} {'95% Hi':>9}  Sig")
    print("  " + "-" * 68)
    for nm, est, sv in zip(pnames, ests, se):
        lo  = est - z95 * sv
        hi  = est + z95 * sv
        sig = "***" if (lo > 0 or hi < 0) else ""
        print(f"  {nm:<24} {est:>9.4f} {sv:>9.4f} {lo:>9.4f} {hi:>9.4f}  {sig}")
    print("  (*** = 95% CI excludes zero)\n")

    print(f"  {'---'*23}")
    print(f"  MODEL FIT  (cf. Das 2025 Table 2)")
    print(f"  AIC  : {aic_v:.2f}   (lower = better fit, penalises parameters)")
    print(f"  BIC  : {bic_v:.2f}   (lower = better fit, stronger penalty)\n")

    print(f"  ECONOMIC INTERPRETATION  (cf. Das 2025 Section 5)")
    print(f"  E[loss | loss>{MU}%, low vol]    ~ {e10:.2f}%")
    print(f"  E[loss | loss>{MU}%, high vol]   ~ {e90:.2f}%")
    print(f"  P(crash | low Nifty vol)      ~ {cp10*100:.1f}%")
    print(f"  P(crash | high Nifty vol)     ~ {cp90*100:.1f}%")
    print(f"  Paper benchmark (MAP-Cauchy)  : <5% at low, >65% at high vol")
    print(sep)


# =============================================================================
# SECTION 8 — MAIN
# =============================================================================

def main():
    print("\n" + "=" * 72)
    print("  CSE 400: Fundamentals of Probability in Computing")
    print("  Group: s2_g16_fin  |  Milestone 3  |  GPD Regression via MLE")
    print("  Reference: Das (2025) arXiv:2506.17549")
    print("=" * 72)

    # ── 1. Data ───────────────────────────────────────────────────────────────
    y, X, cov_raw, scaler = prepare()
    n = len(y)
    print(f"\n  Design matrix X: {X.shape}  ->  [1, nifty_vol, sp500_vol, gold_vol]")
    print(f"  Total tail observations (loss > {MU}%): n = {n}")
    print(f"  NOTE: No train/test split used.")
    print(f"        MLE is a DETERMINISTIC estimator -- uses ALL n observations.")
    print(f"        Train/test split is an ML concept; GPD regression is classical stats.")

    # ── 2. MLE on full data ───────────────────────────────────────────────────
    print("\nFitting GPD Regression via MLE ...")
    res, xi_hat, beta_hat, se = fit_mle(y, X)
    print(f"  Converged       : {res.success}")
    print(f"  Log-likelihood  : {-res.fun:.4f}")
    print(f"  xi (shape)      : {xi_hat:.4f}  (>0 = heavy tail)")
    print(f"  beta (coeffs)   : {np.round(beta_hat, 4)}")
    print(f"  Std errors      : {np.round(se, 4)}")

    # ── 3. Fitted values ──────────────────────────────────────────────────────
    y_fit  = cond_mean(xi_hat, beta_hat, X)
    cp_all = crash_prob(xi_hat, beta_hat, X)
    fin    = np.isfinite(y_fit)
    rmse   = np.sqrt(np.mean((y_fit[fin] - y[fin])**2))
    aic_v, bic_v = aic_bic(res.fun, n=n, k=len(res.x))

    p10  = np.percentile(X[:, 1], 10)
    p90  = np.percentile(X[:, 1], 90)
    med  = np.median(X[:, 2:], axis=0)
    r10  = np.concatenate([[1., p10], med]).reshape(1, -1)
    r90  = np.concatenate([[1., p90], med]).reshape(1, -1)
    cp10 = crash_prob(xi_hat, beta_hat, r10)[0]
    cp90 = crash_prob(xi_hat, beta_hat, r90)[0]
    e10  = cond_mean(xi_hat, beta_hat, r10)[0]
    e90  = cond_mean(xi_hat, beta_hat, r90)[0]
    print(f"  In-sample RMSE  : {rmse:.4f}")

    cov_names = ["b1  Nifty Vol", "b2  S&P 500 Vol", "b3  Gold Vol"]

    # ── 4. Results table ──────────────────────────────────────────────────────
    print_results(xi_hat, beta_hat, se, cov_names, n,
                  aic_v, bic_v, cp10, cp90, e10, e90)

    # ── 5. Plots ──────────────────────────────────────────────────────────────
    print("\n-- Figure 1: Diagnostics --")
    plot_diagnostics(y[fin], y_fit[fin], cp_all[fin],
                     cov_raw[fin, 0], cov_raw[fin, 1], cov_raw[fin, 2])

    print("-- Figure 2: Coefficient forest plot --")
    plot_coefficients(xi_hat, beta_hat, se, cov_names)

    print("-- Figure 3: Crash probability curve --")
    plot_crash_curve(xi_hat, beta_hat, X, scaler)

    print("-- Figure 4: Simulation study --")
    summary, ry, rb, rx, xe, xt = run_simulation(N=100, n=100, p=5)
    plot_simulation(summary, ry, rb, rx, xe, xt)

    print("-- Figure 5: GPD Probability Density Function --")
    plot_pdf(xi_hat, beta_hat, X, y, scaler)

    print("-- Figure 6: GPD Cumulative Distribution Function --")
    plot_cdf(xi_hat, beta_hat, X, y, scaler)

    print("\n  Milestone 3 complete.\n")


if __name__ == "__main__":
    main()